### ISSUE TITLE
docs(readme): missing link to packagist package

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/magento2-cors#1]
1. We should reference the packagist package in the readme. 
2. We should also showcase the numbers of downloads of the package on packagist.

**Comment by kniziol** [comment]
I can do it 🙃

**Comment by damienwebdev** [comment]
@kniziol assigned.

**Comment by kniziol** [comment]
I've created #8 PR with the numbers of downloads badge

**Comment by damienwebdev** [comment]
Fixed by #8

**Comment by kniziol** [comment]
@damienwebdev you're welcome 🙃
