### ISSUE TITLE
[FEAT] Add Magento 2.4 support

### ISSUE THREAD

**Issue by JulianZschieschang** [graycoreio/magento2-cors#33]
# :bulb: Feature request

## The Desired Behavior
Installation of this module works with  Magento 2.4.

## Your Use Case
As a developer I want to use this module in Magento 2.4.

I tried to install this module in the following environment:
<pre><code>magento2-cors version: 1.3.0
Magento version: 2.4.0 
PHP Version version: 7.4.9</code></pre>
and got the following error message:

<pre><code>Problem 1
    - magento/framework 102.0.0 requires php ~7.1.3||~7.2.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.1 requires php ~7.1.3||~7.2.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.2 requires php ~7.1.3||~7.2.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.3 requires php ~7.1.3||~7.2.0||~7.3.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.2-p2 requires php ~7.1.3||~7.2.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.4 requires php ~7.1.3||~7.2.0||~7.3.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.3-p1 requires php ~7.1.3||~7.2.0||~7.3.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.5 requires php ~7.1.3||~7.2.0||~7.3.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.4-p2 requires php ~7.1.3||~7.2.0||~7.3.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - magento/framework 102.0.5-p2 requires php ~7.1.3||~7.2.0||~7.3.0 -> your PHP version (7.4.9) does not satisfy that requirement.
    - graycore/magento2-cors 1.3.0 requires magento/framework ^102.0 -> satisfiable by magento/framework[102.0.5-p2, 102.0.4-p2, 102.0.5, 102.0.3-p1, 102.0.4, 102.0.2-p2, 102.0.3, 102.0.2, 102.0.1, 102.0.0].
    - Installation request for graycore/magento2-cors ^1.3 -> satisfiable by graycore/magento2-cors[1.3.0].
</code></pre>

**Comment by damienwebdev** [comment]
@JulianZschieschang I'll try to get this done over the weekend, apologies on the delay for v2.4 support, been pretty busy. 

If you wanted to contribute, I'd simply need to update the CI to run against php 7.3/7.4 and v2.4. Once we have that, I can figure out what changes we would need to make to iron out 2.4 support.

**Comment by damienwebdev** [comment]
This is closed by various PRs (#34 and #35) culminating in #36.

**Comment by oneserv-heuser** [comment]
@damienwebdev Thanks for fix, but you forgot to bump the version in the composer.json to 1.3.1, so it's still on version 1.3.0 on packagist^^

**Comment by damienwebdev** [comment]
@JulianZschieschang good catch, and thanks for the info. This has been fixed, and I've followed composer guidelines and removed the package version from `composer.json`. The versions are now entirely based upon tags. 

This has been appropriately released as [v1.3.2](https://packagist.org/packages/graycore/magento2-cors#v1.3.2)

**Comment by damienwebdev** [comment]
@JulianZschieschang if you could verify that this works for you, that'd be much appreciated!

**Comment by JulianZschieschang** [comment]
@damienwebdev for me it's working fine. Thanks for the quick fix!
