### ISSUE TITLE
ci(all): add ci pipeline to run unit and integration tests

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/magento2-cors#4]
We should add CI to ensure consistent build quality. Preferably, we should use Azure DevOps.

Currently, while tests are written, they are not run in CI. 

We need to run both the integration and unit tests, and these two processes can be done in parallel.  

See https://github.com/magento/adobe-stock-integration/blob/1.1-develop/.travis.yml as an example of a working Travis sample. We would need to translate this over to Azure Devops and run against PR builds and master.

- [x] Linting (static) (#16 and #17)
- [x] Unit (#18 & #19)
- [ ] Integration
- [ ] Api-Functional

**Comment by geryjuhasz** [comment]
what kind of CI are we talking about ? any specific service ?

**Comment by ferfabricio** [comment]
I can add Travis CI build if needed, please let me know.

**Comment by damienwebdev** [comment]
@geryjuhasz @ferfabricio we tend to use Azure DevOps, but if you have a working TravisCI I can port to Azure DevOps format.

**Comment by ferfabricio** [comment]
@damienwebdev I have a package that was set up with Travis CI and codecov:

https://github.com/tecnospeed/plugnotas-php

If you can I do this setup for this package.

**Comment by damienwebdev** [comment]
@ferfabricio Let's try it with that to start, see if you can get CI passing in your fork. The integration tests have a dependence on the Magento Integration Test Framework, so it may be more complicated than the setup in that package.

**Comment by damienwebdev** [comment]
@geryjuhasz I've updated the description to include the ideal services, but as I said, if you can write it on a particular service and get it to work, I'll port it over to what will work for me.

**Comment by geryjuhasz** [comment]
Sounds good, thank you
