### ISSUE TITLE
Magento Rest Options Error

### ISSUE THREAD

**Issue by gilbert-rehling** [graycoreio/magento2-cors#54]
Hi, 
    I was using the SplashLabs CORS module, but ran into a blocker with it when trying to POST to the guest-cart. 
I disabled it and installed your module, added the configs etc etc.

Now I can't even see the initial API GET product request work anymore.
We are using Magento 2.3.3 (commerce) on Magento Cloud - working on Integration instance.

In the exception I see:
[2021-03-09 05:45:50] report.CRITICAL: Request method is invalid. {"report_id":"076a55918ca8c940a9c25f3cc440482a965e1d6ed7b7e24d647dbc8906e6b43d","exception":"[object] (Magento\\Framework\\Exception\\InputException(code: 0): Request method is invalid. at /app/vendor/magento/framework/Webapi/Rest/Request.php:180)"} []

Which closely matched an access log:
193.114.101.142 - - [09/Mar/2021:05:45:50 +0000] "OPTIONS /rest/V1/products?&searchCriteria[filter_groups][0][filters][0][field]=entity_id&searchCriteria[filter_groups][0][filters][0][value]=3019&searchCriteria[filter_groups][0][filters][0][condition_type]=eq HTTP/1.1" 500 501 "https://crv-test5.racingjd.com/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.190 Safari/537.36"

I notice that in your module your not overriding the ->getHttpMethod() which by default does not recognise OPTIONS method (which is inherently the Magento shortcoming)

Did we miss something in the setup?
The module was active, and cached were flushed after the deployment..  I even tried a few different option variations..

Thnx...

**Comment by damienwebdev** [comment]
@gilbert-rehling I have never tried this against Commerce Cloud, only against Open Source edition. 

We catch the preflight check before the "getHttpMethod" is called, so we never hit the method verification.

Looking at the error, it seems like the module isn't enabled, as we have an integration test that covers making requests to the REST API.

I'm also suspicious of another plugin running before dispatch that is also checking that same method.

Regardless, I think it is reasonable to update that method to allow options.

**Comment by damienwebdev** [comment]
@gilbert-rehling did this work for you?

**Comment by gilbert-rehling** [comment]
Hi,  yes it worked.  I was able to reach the same point as before.
However, I am still getting the same error in Chrome, when I try to POST
with a Payload to ~/guest-cart/<cart id>/items.

Unfortunately I'll have to dig deeper to find a solution.  If I can
determine that is a CORS module issue I will let you know.
For now, I'm using Firefox to continue my DEV work as its' not affected by
the problem.

Thank You,
                  Gilbert Rehling

4/475 Vulture Street E, East Brisbane QLD 4169
+61 0474 815 662

**Comment by damienwebdev** [comment]
@gilbert-rehling are you able to paste a screenshot of the error you get, or a stack trace? That will help determine whether not the issue is in the scope of this package.

**Comment by damienwebdev** [comment]
@gilbert-rehling I have released this as v1.5.0. Thanks for the bug report!
