### ISSUE TITLE
feat(cors): add support for Access-Control-Expose-Headers

### ISSUE THREAD

**Issue by damienwebdev** [graycoreio/magento2-cors#6]
Currently, we only support a subset of the CORS protocol. We should extend support to `Access-Control-Expose-Headers`

https://fetch.spec.whatwg.org/#http-access-control-expose-headers

**Comment by rasmuswikman** [comment]
This would be really cool. 👍 

Got stuck with Apollo GraphQL at this because headers are not allowed.

```
const consoleLink = new ApolloLink((operation, forward) => {
    return forward(operation).map((data) => {
        const context = operation.getContext();
        const { response: { headers } } = context;
        if (headers) {
            const token = headers.get('x-session-token');

            if (token) {
                localStorage.setItem('token', token);
            }
        }
        return data;
    })
});
```

**Comment by damienwebdev** [comment]
@rasmuswikman  I read through the spec. This should be fairly straightforward to implement. I'll submit a PR for you to try out.
