### ISSUE TITLE
[OTHER] How to use on Magento Cloud

### ISSUE THREAD

**Issue by rahulblue** [graycoreio/magento2-cors#78]
We have tried to installed your module into Magento Cloud, We followed all initial steps which you given. we were trying to add system variable which you mentioned here - https://github.com/graycoreio/magento2-cors/blob/master/docs/stories/configuring-the-headers.md, but in Magento cloud env.php file is not editable, also there isn't any provision to add system variable into anywhere.

Do you have any other solution for adding all values under system? adding somewhere in config or .php file?

## Environment

magento2-cors version: 1.6.0
Magento version: Magento Commerce 2.4.5
PHP Version version: 8.1

**Comment by damienwebdev** [comment]
@rahulblue you can make this work by using the cloud UI for managing ENV settings.

The relevant document would be:

https://experienceleague.adobe.com/docs/commerce-cloud-service/user-guide/configure/env/variable-levels.html?lang=en

https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-var-name.html

You'll like need to set

`env:CONFIG__SYSTEM__WEB__GRAPHQL__CORS_ALLOWED_ORIGINS` in the UI.

**Comment by damienwebdev** [comment]
Additionally, I would recommend giving 2.0 a  try as well, it's ~10x faster than the 1.x line.

**Comment by rahulblue** [comment]
> env:CONFIG__SYSTEM__WEB__GRAPHQL__CORS_ALLOWED_ORIGINS

I have tried using this method but again having a same problem
![3795a25e-9fa7-4daf-870a-0a2612c20013](https://user-images.githubusercontent.com/16150494/212338936-986421a4-6591-47c5-95bd-79c73a2d6530.jpg)
.
![b359b61d-6a3c-40c3-8636-499f1ea9e3c4](https://user-images.githubusercontent.com/16150494/212339079-5c20c0b2-004c-434e-93ee-b5bb1ac85e76.jpg)

**Comment by damienwebdev** [comment]
Please re-read the documents I sent.

**Comment by rahulblue** [comment]
Exactly which point are you referring to the problem is in there is no .magento.env.yaml file in the setup, only way I have that creating environment variable from Cloud UI, but it is not working. I am researching this topic since from last 9 hour still do not have exact solution.

**Comment by damienwebdev** [comment]
https://devdocs.magento.com/guides/v2.3/config-guide/prod/config-reference-var-name.html#variable-names

Additionally, take a look at your screenshot and try to align:

1. What you wrote in the variable name 
2. What you pasted into the variable value
3. What I wrote in the docs for the variables of this repo

It looks like you literally copy-pasted some access control headers into the field, which I don't mention anywhere in my docs.

**Comment by rahulblue** [comment]
Thanks for your reply,

Can you see below screenshot? Am I missing or doing wrongly?

please suggest.
![e2f57ac1-2cf1-4b26-9cc9-3187b7c37d83](https://user-images.githubusercontent.com/16150494/212351538-3fdb4dbf-7d03-4d3a-899a-2c93b59cfa00.jpg)
![9fe9a0ad-a78a-4b2d-ac1d-ac9e30da2c18](https://user-images.githubusercontent.com/16150494/212351582-f9b974b5-dcc3-4d15-9ce3-4892e73e29d9.jpg)

**Comment by rahulblue** [comment]
No luck after updating.

same error 
![334f03d3-3adb-4bd4-8515-14413dad6d28](https://user-images.githubusercontent.com/16150494/212360453-0e3391df-d017-4bf8-aba2-0dcddd131444.jpg)
![7100c28a-602f-4fdc-b5c4-cd29b539499e](https://user-images.githubusercontent.com/16150494/212360544-80e96ebd-8450-44db-98b5-27216382a914.jpg)

**Comment by damienwebdev** [comment]
Ok, let me try this out and I'll post my findings.

**Comment by rahulblue** [comment]
please let me know your findings, I have only one hope which is your extension. for Magento cloud integration branch there is no other way to enable CORS settings, it would be enable on further environment(Staging and Production) due to fastly. currently it is a biggest bottleneck for moving ahead to me.

Thanks.

**Comment by damienwebdev** [comment]
I don't have a cloud account that I have permissions to deploy this to. If
you have one, I'd be more than happy to help.

**Comment by leandrofreireasco** [comment]
@damienwebdev I'm working on a cloud project right now.
Our stack is Angular (Frontend) and Magento Cloud.
We are getting issues with CORS while trying to fetch data from a graphql endpoint.
I've installed your module and tried to configure it: 
* Environment variables:
-- CONFIG__DEFAULT__WEB__GRAPHQL__CORS_ALLOWED_ORIGINS
-- CONFIG__DEFAULT__WEB__GRAPHQL__CORS_ALLOWED_METHOD

* Adding to the app/etc/config.php (we don't have access to the env.php in Magento Cloud)

* Adding the XML paths directly into the core_config_data

None of the steps above works

Any other clue on what we could do?

**Comment by damienwebdev** [comment]
Can you include the output headers on an OPTIONS request with curl targeted at your domain?

```bash 
curl https://DOMAIN.com/graphql \
   -X OPTIONS \
   -H "Access-Control-Request-Method: POST" \
   -H "Access-Control-Request-Headers: content-type" \
   -H "Origin: https://DOMAIN.com"
```

**Comment by leandrofreireasco** [comment]
@damienwebdev just to let you know, I figured it out.

In order for this module to work with Magento Cloud, we need to add the following entries to the app/etc/config.php file:

` 'system' => [
        'default' => [
            'web' => [
                'graphql' => [
                    'cors_allowed_origins' => '*',
                    'cors_allowed_methods' => 'GET, POST, OPTIONS, PUT',
                    'cors_allowed_headers' => 'Content-Type, GraphQLAuth', // All headers used in the request
                    'cors_max_age' => '86400',
                    'cors_allow_credentials' => 0
                ],
                'api_rest' => [
                    'cors_allowed_origins' => '*',
                    'cors_allowed_methods' => 'GET, POST, OPTIONS',
                    'cors_allowed_headers' => 'Content-Type, GraphQLAuth' // All headers used in the request,
                    'cors_max_age' => '86400',
                    'cors_allow_credentials' => 0
                ]
            ]
        ]
    ]`

**Comment by leandrofreireasco** [comment]
yep, those 3 headers must exist:
- cors_allowed_origins
- cors_allowed_methods
- cors_allowed_headers

**Comment by damienwebdev** [comment]
@leandrofreireasco ok. Then, for the origins, I assume you added those as ENV variables to the cloud UI? Could you add a screenshot of what you added? (Feel free to obfuscate this, I just need a screenshot for the documentation)

**Comment by amcguireweb** [comment]
Funny you mention "for the documentation", I literally see no documentation to use this with Cloud. Trying to piece together a couple random issues with no solutions isn't working. Uninstalled as fast as I installed it.

**Comment by damienwebdev** [comment]
Sorry @amcguireweb I don't have any merchants that use this on Commerce Cloud. If you're willing to hop in discord, I'd be happy to turn whatever comes out of that into docs, it's just hard to write docs for something I don't do!

**Comment by leandrofreireasco** [comment]
Here we go @damienwebdev 

app/etc/config.php

<img width="1891" alt="image" src="https://github.com/graycoreio/magento2-cors/assets/124809558/a05ed55b-57a2-4bce-b1df-053d2353ce21">

.magento.app.yaml

<img width="988" alt="image" src="https://github.com/graycoreio/magento2-cors/assets/124809558/8ee4fb01-62b0-4832-81b1-a524e6b7edb6">
