### ISSUE TITLE
Using Varnish Cache with PWA Stuido

### ISSUE THREAD

**Issue by secaliskan** [graycoreio/magento2-cors#86]
# :bulb: Feature request

## Feature Name
PWA Stuido GraphQL POST request Fix for Varnish cache 

## The Desired Behavior
When we activate Varnish cache at Magento backend also update the default.vcl at varnish server; PWA stuid frontend working fine;
GET queries are cacheable - should be working
POSt request are not cacheable -should be working

## Your Use Case
Varnish enabled n different server with IP; backlend is in the same env with internal ip does not have a public IP
Varnish configuration on Magento Admin has been set correctly.
Exported varnish VCL updated in Varnsh server.
Website is working and Varnish caching is working
When we see the network GraphQL GET queries working fine. we can render catalog and product pages.

But whem we come to graphql POST request its giving 500 Internal server error.
IMO Get query content-type are application/json
But POST actions content-type is text/html

So its giving Internal Server error 500

## Environment

<pre><code>
magento2-cors version:  I dont know
Magento version: 2.4.5 p1
PHP Version version: 8.1
Varnish cache: Verison 6.012

Varnish cache is at another Server with Public IP ; Magento app server is in different server. with internal IP..

Others:

</code></pre>

**Comment by damienwebdev** [comment]
Why do you think this is an error with the CORS plugin?
